const data = {
    0: {
        id: "0931594952",
        firstName: "Luciana",
        lastName: "Tzefanyah",
        history: [
            {
                id: 1,
                beginning: "07.09.2015 (8:37)",
                end: "08.09.2015 (8:20)",
                duration: "23:47 Hours",
                numberOfMeasurements: 77,
                successfulMeasurements: 76,
            },
            {
                id: 2,
                beginning: "06.04.2018 (9:37)",
                end: "07.04.2018 (10:20)",
                duration: "24:47 Hours",
                numberOfMeasurements: 77,
                successfulMeasurements: 50,
            }
        ],
        tags: ["0931594952", "Luciana", "Tzefanyah",
            "luciana", "tzefanyah", "Luciana Tzefanyah",
            "luciana tzefanyah"],
    },
    1: {
        id: "0710439024",
        firstName: "Zifa",
        lastName: "Atli",
        history: [
            {
                id: 1,
                beginning: "07.04.2019 (6:00)",
                end: "08.04.2019 (24:00)",
                duration: "10 Hours",
                numberOfMeasurements: 80,
                successfulMeasurements: 75,
            },
        ],
        tags: ["0710439024", "Zifa", "Atli",
            "zifa", "atli", "Zifa Atli",
            "zifa atli"],
    },
    2: {
        id: "0889205515",
        firstName: "Kallisto",
        lastName: "Helge",
        history: [
            {
                id: 1,
                beginning: "07.04.2018 (6:00)",
                end: "08.04.2018 (24:00)",
                duration: "18 Hours",
                numberOfMeasurements: 90,
                successfulMeasurements: 75,
            },
        ],
        tags: ["0889205515", "Kallisto", "Helge",
            "kallisto", "helge", "Kallisto Helge",
            "kallisto helge"],
    },
    3: {
        id: "0317004670",
        firstName: "Thelma",
        lastName: "Manju",
        history: [
            {
                id: 1,
                beginning: "07.04.2014 (6:00)",
                end: "08.04.2014 (24:00)",
                duration: "4 Hours",
                numberOfMeasurements: 90,
                successfulMeasurements: 80,
            },
            {
                id: 2,
                beginning: "07.04.2017 (6:00)",
                end: "08.04.2017 (24:00)",
                duration: "12 Hours",
                numberOfMeasurements: 100,
                successfulMeasurements: 75,
            },
            {
                id: 3,
                beginning: "07.04.2018 (6:00)",
                end: "08.04.2018 (24:00)",
                duration: "7 Hours",
                numberOfMeasurements: 95,
                successfulMeasurements: 75,
            },
        ],
        tags: ["0317004670", "Thelma", "Manju",
            "thelma", "manju", "Thelma Manju",
            "thelma manju"],
    },
    4: {
        id: "0687845412",
        firstName: "Alexandrea",
        lastName: "Lucija",
        history: [
            {
                id: 1,
                beginning: "07.04.2014 (6:00)",
                end: "08.04.2014 (24:00)",
                duration: "4 Hours",
                numberOfMeasurements: 90,
                successfulMeasurements: 80,
            },
            {
                id: 2,
                beginning: "07.04.2017 (6:00)",
                end: "08.04.2017 (24:00)",
                duration: "12 Hours",
                numberOfMeasurements: 100,
                successfulMeasurements: 75,
            },
        ],
        tags: ["0687845412", "Alexandrea", "Lucija",
            "alexandrea", "lucija", "Alexandrea Lucija",
            "alexandrea lucija"],
    },
    5: {
        id: "0448418959",
        firstName: "Astride",
        lastName: "Dzintars",
        history: [
            {
                id: 1,
                beginning: "07.04.2016 (6:00)",
                end: "08.04.2016 (24:00)",
                duration: "4 Hours",
                numberOfMeasurements: 65,
                successfulMeasurements: 60,
            },
        ],
        tags: ["0448418959", "Astride", "Dzintars",
            "astride", "dzintars", "Astride Dzintars",
            "astride dzintars"],
    },
    6: {
        id: "0815749814",
        firstName: "Nsia",
        lastName: "Erland",
        history: [],
        tags: ["0815749814", "Nsia", "Erland",
            "nsia", "erland", "Nsia Erland",
            "nsia erland"],
    },
}

export default data;
